// packages/__development/mylib/mo-solid/mount-app-root.ts
import { JSX } from "solid-js/jsx-runtime";
import { render } from "solid-js/web";

type RootElement = HTMLElement & { __disposeRender?: () => void };

export function mountAppRoot(fn: () => JSX.Element, rootElementId = "app") {
  const root = document.getElementById(rootElementId)! as RootElement;
  root.__disposeRender?.(); //cleanup previous dom
  root.__disposeRender = render(fn, root);
}

// unit-examples/lib/mo-react/mount-app-root.ts
import { ReactNode } from "react";
import { createRoot, Root } from "react-dom/client";

type RootElement = HTMLElement & { __reactRoot: Root };

export function mountAppRoot(rootNode: ReactNode, rootElementId = "app") {
  const appDiv = document.getElementById(rootElementId) as RootElement;
  appDiv.__reactRoot ??= createRoot(appDiv);
  appDiv.__reactRoot.render(rootNode);
}
