// __development/app3-react/src/components/number-slider-box.tsx
import { KnobFrame } from "beams/mo-react/components/knob-frame";

export function NumberSliderBoxView(props: {
  value: number;
  fracDigits?: number;
}) {
  return (
    <div className="border border-[#444] w-[60px] h-[34px] flex-c">
      {props.value.toFixed(props.fracDigits ?? 2)}
    </div>
  );
}

export function NumberSliderBox({
  label,
  value,
  min = 0,
  max = 100,
  step = 1,
  fracDigits = 0,
  onChange,
}: {
  label?: string;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  fracDigits?: number;
  onChange: (value: number) => void;
}) {
  return (
    <div className="flex-ha gap-1">
      {label && <div>{label}</div>}
      <KnobFrame
        value={value}
        min={min}
        max={max}
        step={step}
        onChange={onChange}
      >
        <NumberSliderBoxView value={value} fracDigits={fracDigits} />
      </KnobFrame>
    </div>
  );
}

// packages/__development/mylib/mo-solid/components/number-slider-box.tsx
import { mergeProps } from "solid-js";
import { CellFrame } from "./cell-frame";
import { KnobFrame } from "./knob-frame";

export function NumberSliderBoxView(props: {
  value: number;
  fracDigits?: number;
}) {
  return (
    <div class="border border-[#444] w-[48px] h-[28px] flex-c">
      {props.value.toFixed(props.fracDigits ?? 2)}
    </div>
  );
}

export function FeNumberSliderBox(inputProps: {
  label: string;
  value: number;
  min?: number;
  max?: number;
  step?: number;
  fracDigits?: number;
  onChange: (value: number) => void;
}) {
  const props = mergeProps(
    { min: 0, max: 1, step: 0.01, fracDigits: 2 },
    inputProps,
  );
  return (
    <CellFrame label={props.label}>
      <KnobFrame
        value={props.value}
        min={props.min}
        max={props.max}
        step={props.step}
        onChange={props.onChange}
      >
        <NumberSliderBoxView
          value={props.value}
          fracDigits={props.fracDigits}
        />
      </KnobFrame>
    </CellFrame>
  );
}
