// apps/app3-react/src/host-system/react/frame-size.ts
export type Size = { width: number; height: number };
export type FrameSizeInput = Size | [number, number] | string;

export function normalizeFrameSize(
  size: FrameSizeInput | undefined,
): Size | undefined {
  if (Array.isArray(size)) {
    return { width: size[0], height: size[1] };
  } else if (typeof size === "string") {
    if (size.includes(",")) {
      const [width, height] = size.split(",").map((s) => Number(s.trim()));
      return { width, height };
    } else if (size.includes("x")) {
      const [width, height] = size.split("x").map((s) => Number(s.trim()));
      return { width, height };
    }
  } else if (typeof size === "object") {
    return size;
  }
  return undefined;
}

export function mergeStyleWithFrameSize(
  style?: React.CSSProperties,
  size?: FrameSizeInput,
): React.CSSProperties | undefined {
  if (!style && !size) return undefined;
  const normalizedSize = normalizeFrameSize(size);
  if (!normalizedSize) return style;
  return {
    ...style,
    width: `${normalizedSize.width}px`,
    height: `${normalizedSize.height}px`,
  };
}

// __development/framework/packages/wus-host-system/solid/frame-size.ts
import { JSX } from "solid-js";

export type Size = { width: number; height: number };
export type FrameSizeInput = Size | [number, number] | string;

export function normalizeFrameSize(
  size: FrameSizeInput | undefined,
): Size | undefined {
  if (Array.isArray(size)) {
    return { width: size[0], height: size[1] };
  } else if (typeof size === "string") {
    if (size.includes(",")) {
      const [width, height] = size.split(",").map((s) => Number(s.trim()));
      return { width, height };
    } else if (size.includes("x")) {
      const [width, height] = size.split("x").map((s) => Number(s.trim()));
      return { width, height };
    }
  } else if (typeof size === "object") {
    return size;
  }
  return undefined;
}

export function mergeStyleWithFrameSize(
  style?: JSX.CSSProperties,
  size?: FrameSizeInput,
): JSX.CSSProperties | undefined {
  if (!style && !size) return undefined;
  const normalizedSize = normalizeFrameSize(size);
  if (!normalizedSize) return style;
  return {
    ...style,
    width: `${normalizedSize.width}px`,
    height: `${normalizedSize.height}px`,
  };
}
